vich_uploader:
    db_driver: orm

    mappings:
       vehicle_images:
           uri_prefix: /img/vehicles
           upload_destination: '%kernel.project_dir%/public/assets/img/vehicles'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
